"""Make sales fields nullable

Revision ID: 605c4f306296
Revises: 96f5aa4d1044
Create Date: 2025-06-03 04:09:57.267043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605c4f306296'
down_revision = '96f5aa4d1044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('product',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('region',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('revenue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('revenue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('region',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('product',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
